version: 2

sources:
  - name: olist_raw
    database: OLIST_DB
    schema: RAW
    tables:
      - name: orders
      - name: customers
      - name: productivity
      - name: payments
      - name: sellers
      - name: products
      - name: order_items
      - name: order_reviews
      - name: category_name_translation